swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:

  /user/accounts/{accountId}:
    get:
      tags:
        - Accounts Module
      summary: Account detail
      description: API for retrieving account details
      parameters:
        - in: header
          name: token
          type: integer
          description: token of the account
          required: true
        - in: path
          name: accountId
          type: integer
          description: accountId of the account
          required: true
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        "200":
          description: User account has been successfully retrieved
          schema:
            $ref: "#/definitions/accountId"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Token is missing or invalid
        "403":
          description: Forbidden - User does not have permission
        "500":
          description: Internal Server Error
          
  /user/accounts/{accountId}/{month}/transactionsList:
    get:
      tags:
        - Accounts Module
      summary: Get all transactions for the current month
      description: "Retrieve a list of transactions for the current month, for the selected account"
      parameters:
        - in: header
          name: token
          type: integer
          description: token of the account
          required: true
        - in: path
          name: accountId
          type: integer
          description: ID of the account
          required: true
        - in: path
          name: month
          type: string
          description: month parameter
          required: true
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: "#/definitions/transactionsList"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Token is missing or invalid
        "403":
          description: Forbidden - User does not have permission
        "500":
          description: Internal Server Error
        

  /transactionsList/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Get details of a specific transaction
      description: "Retrieve detailed informations about a specific transaction"
      security:
        - Bearer: []
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: "#/definitions/transactionDetails"
        "401":
          description: Unauthorized - Token is missing or invalid
        "403":
          description: Forbidden - User does not have permission
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

    put:
      tags:
        - Transactions Module
      summary: Update information of a specific transaction
      description: >-
        Update details of a specific transaction (only 'Category' and 'Note' can
        be modified)
      security:
        - Bearer: []
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction payload
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
      produces:
        - application/json
      responses:
        "200":
          description: Transaction's informations have been successfully modified
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Token is missing or invalid
        "403":
          description: Forbidden - User does not have permission
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
          
definitions:
  accounts:
    type: object
    properties:
      accounts:
        type: array
        items:
          $ref: "#/definitions/accounts"

  accountId:
    type: object
    properties:
      accountId:
        type: number
        description: account id
      name:
        type: string
        description: account name
      balance:
        type: number
        description: account balance
        
  month:
    type: object
    properties:
      month:
        type: string
        items:
          $ref: "#/definitions/month"
        
  transactionsList:
    type: object
    properties:
      transactionsList:
        type: array
        items: 
          $ref: "#/definitions/transactionDetails"
        description: List of the transactions

  transactionDetails:
    type: object
    properties:
      transactionId:
        type: string
        description: ID of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: amount number
      balance:
        type: number
        description: Balance after the transaction
      transactionType:
        type: string
        description: transaction type
  UpdateTransaction:
    type: object
    properties:
      category:
        type: string
        description: Updated category of the transaction
      note:
        type: string
        description: Updated note for the transaction
    required:
      - category
      - note
    additionalProperties: false
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string


